version: '3.7'

services:

  joomla:
    image: joomla-debug:3.10.11
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
      - 9191:443
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes: 
      - "./www:/var/www/html"


  joomladb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      