#!/bin/bash

PREFIX='ukrgb'
APP_NAME='test'  #'test' or 'river'
COMPONENT="com_ukrgbmap"
APP="${PREFIX}-${APP_NAME}-app"

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
temp_dir=$(mktemp -d)
component_dir="$PROJECT_ROOT/$COMPONENT"

# copy the component files to create the working copy
rsync -a --exclude=".*"  "$component_dir" "$temp_dir"

##
#  Build the embedded App
##
cd "$PROJECT_ROOT/$APP" || exit
yarn build

# Gen the name of the .js and .css generated by the build
manifest=$PROJECT_ROOT/$APP/dist/.vite/manifest.json 
js=$(jq --raw-output '."index.html".file' "$manifest")
css=$(jq --raw-output '."index.html".css[0]' "$manifest")

# Check there arn't multiple CSS files, this is not expected or handled
nextCSS=$(jq '."index.html".css[1]' "$manifest") 
if [ "$nextCSS" != "null" ]; then 
    echo "ERROR: Multiple .css files found in build manifest $manifest"
    exit 1
fi

# Copy generated files in to the media folder of the working copy of 
# the component
media=$temp_dir/$COMPONENT/media
cp "$PROJECT_ROOT/$APP/dist/$js" "$media/js/"
cp "$PROJECT_ROOT/$APP/dist/$css" "$media/css/"

# Update the ./media/joomla.asset.json in the working copy withe the 
# filenames of the .js and .css files for the map application
index=0
for a in $(jq -c '."assets".[]' "$media/joomla.asset.json") ;do
    name=$(jq -r '."name"' <<< "$a")
    case $name in
    #com_ukrgbmap.mapjs
    "$COMPONENT/mapjs")
        tmp=$(mktemp)
        uri="$COMPONENT/"$(basename "$js")
        jq '."assets".['$index'].uri = "'"$uri"'"' "$media/joomla.asset.json" > "$tmp"
        mv "$tmp" "$media/joomla.asset.json"
    ;;
    "$COMPONENT/mapcss")
        tmp=$(mktemp)
        uri="$COMPONENT/"$(basename "$css")
        jq '."assets".['$index'].uri = "'"$uri"'"' "$media/joomla.asset.json" > "$tmp"
        mv "$tmp" "$media/joomla.asset.json"
    ;;
    esac
    ((index++))
done

rm "$PROJECT_ROOT"/packagefiles/*.zip

# Make the Component .zip package
echo "Component, Creating Zip..."
cd "$temp_dir" || exit
zip -qr "$PROJECT_ROOT/packagefiles/$COMPONENT" .
rm -rf "$temp_dir"

# Make the Library .zip package
echo "Library Creating Zip..."
cd "$PROJECT_ROOT"/lib_ukrgbgeo || exit
zip -qr ../packagefiles/lib_ukrgbgeo .

# Make the Plugin .zip package

if [ "$APP_NAME" == "river" ]; then
    echo "Plugin Creating Zip..."
    cd "$PROJECT_ROOT"/plg_ukrgbmap || exit
    zip -qr "$PROJECT_ROOT/packagefiles/plg_ukrgbmap" .
else
    echo "Test Plugin Creating Zip..."
    cd "$PROJECT_ROOT"/plg_ukrgbtest || exit
    zip -qr "$PROJECT_ROOT/packagefiles/plg_ukrgbtest" .
fi

echo "Done."